### ISSUE TITLE
Type!!!

### ISSUE THREAD

**Issue by hejrhehe** [Kinlei/MaterialLua#3]
when I type

Z.TextField([

Text = "Name",
Type = "Password",
Callback = function(value)
print(`value`)
end
)]

nothing shows up!!!

**Comment by hejrhehe** [comment]
plz help 🙁

**Comment by aKinlei** [comment]
Hi, I have no idea what's causing this issue. I have had no problems, personally.

**Comment by papycochon** [comment]
```
Text = "Name",
Type = "Password",
Callback = function(value)
print(value)
end
])
```
easy win no need to test use your brain next time

**Comment by technorav3nn** [comment]
@papycochon Can you help me with toggles?

So i usually used wally v3 ui lib, and toggles were fine, but how do I return the state of toggle?

Basically I just want it so that if its switched on it will return true and run the true script, and if its off it will return false and return the false script.

Kinda confused whilst reading the documentation, thanks
I tried using return with getstate() but im still confused, thx
And  also, I want to loop the function but you cant break it in a else statement

**Comment by Kinlei** [comment]
Use ({}) instead of ([]).
